# Домашнее задание "Линейная алгебра. Матрицы".

## Уровень 0:


### Задание 1

 - Создайте матрицу 3 на 3, заполненную числами от 1 до 9
 - Прибавьте к ней матрицу с единицами на диагонале
 - Умножьте полученную матрицу на вектор (1, 2, 3)
 - Вычислить транспонированную матрицу $A^T$ от полученной в результате прибавления матрицы
 - Посчитайте обратную матрицу к полученной в результате прибавления матрице


In [1]:
import numpy as np

In [2]:
# Создайте матрицу 3 на 3, заполненную числами от 1 до 9
M = np.array(range(1,10)).reshape(3, 3)
M

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
# Прибавьте к ней матрицу с единицами на диагонале
M1 = M + np.eye(3)
M1

array([[ 2.,  2.,  3.],
       [ 4.,  6.,  6.],
       [ 7.,  8., 10.]])

In [4]:
# Умножьте полученную матрицу на вектор (1, 2, 3)
M1 * np.array([1, 2, 3])

array([[ 2.,  4.,  9.],
       [ 4., 12., 18.],
       [ 7., 16., 30.]])

In [5]:
# Вычислить транспонированную матрицу 𝐴𝑇 от полученной в результате прибавления матрицы
np.transpose(M1)

array([[ 2.,  4.,  7.],
       [ 2.,  6.,  8.],
       [ 3.,  6., 10.]])

In [6]:
# Посчитайте обратную матрицу к полученной в результате прибавления матрице
np.linalg.inv(M1)

array([[-6. , -2. ,  3. ],
       [-1. ,  0.5,  0. ],
       [ 5. ,  1. , -2. ]])

## Уровень 1:

### Задание 2

Найдите собственные значения и собственные вектора матрицы:
```
m = np.array([[2, 2],
              [1, 3]])
print(m)
```



In [7]:
m = np.array([[2, 2], [1, 3]])
m

array([[2, 2],
       [1, 3]])

In [8]:
# собственные значения
eig = np.linalg.eig(m)
eig[0]

array([1., 4.])

In [9]:
# собственные вектора
vecs = np.transpose(eig[1])
vecs[0], vecs[1]

(array([-0.89442719,  0.4472136 ]), array([-0.70710678, -0.70710678]))

### Задание 3


Придумайте матрицу, у которой определитель = 1, и все элементы не равны 0.

P.S. Матрица должна быть ненулевой и размерностью не менее 2! 

In [10]:
A = np.array([[2, 5, 8], [2, 4, 10], [2, 6, 5.5]])
A

array([[ 2. ,  5. ,  8. ],
       [ 2. ,  4. , 10. ],
       [ 2. ,  6. ,  5.5]])

In [11]:
np.linalg.det(A)

1.0